Nueva carpeta/Login/Login.web/Models/ErrorViewModel.cs
using System;

namespace Login.web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Nueva carpeta/Login/Login.web/Models/LiteDBConfig.cs
namespace Login.web.Models
{
    public class LiteDBConfig
    {
        public string DatabasePath { get; set; }
    }
}

Nueva carpeta/Login/Login.web/Models/LiteDBContext.cs
using System;
using LiteDB;
using Microsoft.Extensions.Options;

namespace Login.web.Models
{
    public class LiteDBContext
    {
        public readonly LiteDatabase Context;
        public LiteDBContext(IOptions<LiteDBConfig> configs)
        {
            try
            {
                var db = new LiteDatabase(configs.Value.DatabasePath);
                if (db != null)
                    Context = db;
            }
            catch (Exception ex)
            {
                throw new Exception("No se encuentra o no se puede crear LiteDB.", ex);
            }
        }
    }
}

Nueva carpeta/Login/Login.web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Login.web.Models;

namespace Login.web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Nueva carpeta/Login/Login.web/Controllers/ModuloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Login.web.Controllers
{
    public class ModuloController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Nueva carpeta/Login/Login.web/Controllers/UsuarioController.cs
using Login.web.Models;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using System;

namespace Login.web.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly LiteDBContext db;

        public UsuarioController(LiteDBContext db)
        {
            this.db = db;
        }


        [HttpGet]
        public IActionResult Index()
        {
            
            var usuarios = db.Context.GetCollection<Usuario>("Usuarios");

          
            ViewBag.CantidadUsuarios = usuarios.Count();

          
            return View("Index", usuarios.FindAll());
        }

        [HttpGet]
        public IActionResult Agregar()
        {
            return View("Agregar");
        }

        [HttpPost]
        public IActionResult Agregar(Usuario usuario)
        {
            var usuarios = db.Context.GetCollection<Usuario>("usuarios");
            usuario.idUsuario = Convert.ToString(Guid.NewGuid());
            usuarios.Insert(usuario);
            return RedirectToAction("Index", usuarios.FindAll());
        }

        [HttpGet]
        public IActionResult Editar(int id)
        {
            var usuarios = db.Context.GetCollection<Usuario>("usuarios").FindAll();

            var usuario = usuarios.FirstOrDefault(x => x.id == id);

            return View("Editar", usuario);
        }

        [HttpPost]
        public IActionResult Editar(Usuario usuario)
        {
            var usuarios = db.Context.GetCollection<Usuario>("usuarios");

         
            usuarios.Update(usuario);

            return RedirectToAction("Index", usuarios.FindAll());
        }
        public IActionResult Eliminar(int id)
        {
            var usuarios = db.Context.GetCollection<Usuario>("usuarios");

           
            usuarios.Delete(x => x.id == id);

            return RedirectToAction("Index", usuarios.FindAll());
        }
    }
}

Nueva carpeta/Login/Login.web/Controllers/empresaController.cs
using Login.web.Models;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using System;

namespace Login.web.Controllers
{
    public class EmpresaController : Controller
    {
        private readonly LiteDBContext db;

        public EmpresaController(LiteDBContext db)
        {
            this.db = db;
        }


        [HttpGet]
        public IActionResult Index()
        {

            var empleados = db.Context.GetCollection<Usuario>("Usuarios");


            ViewBag.CantidadEmpleados = empleados.Count();


            return View("Index", empleados.FindAll());
        }

        [HttpPost]
        public IActionResult Agregar(Usuario usuario)
        {
            var usuarios = db.Context.GetCollection<Usuario>("Usuarios");
            usuario.idUsuario = Convert.ToString(Guid.NewGuid());
            usuarios.Insert(usuario);
            return RedirectToAction("Index", usuarios.FindAll());
        }
    }
}

Nueva carpeta/Login/Login.web/Views/Empresa/Index.cshtml
@model IEnumerable<Login.Usuario>

<div class="row">
    <div class="col-10">
        <h2 class="display-4">Empleados</h2>
    </div>
</div>
<br />
<br />
<p>Cantidad de Empleados: <b>@ViewBag.CantidadEmpleados</b></p>
<table class="table table-dark table-striped table-responsive-md">
    <thead>
        <tr>
            <th>Usuario </th>

            <th>Nombre </th>

            <th>Apellido </th>

            <th>DNI </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var usuario in Model)
        {
        <tr>
            <td>@usuario.nombreUsuario</td>
            <td>@usuario.nombre</td>
            <td>@usuario.apellido</td>
            <td>@usuario.dni</td>
        </tr>
        }
    </tbody>
</table>

Nueva carpeta/Login/Login.web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Nueva carpeta/Login/Login.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Login.web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Login.web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Usuario" asp-action="Index">Usuarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Empresa" asp-action="Index">Empresa</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Login.web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Nueva carpeta/Login/Login.web/Views/Usuario/Agregar.cshtml
@model Login.Usuario

<h1 class="display-5 mt-5">Nuevo Usuario</h1>

<form asp-controller="Usuario" asp-action="Agregar" method="post">
    <div class="form-group">
        <label for="exampleInputEmail1">Username</label>
        <input asp-for="nombreUsuario" type="text" placeholder="Nombre de usuario" class="form-control" />
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input asp-for="contrasenia" type="password" placeholder="Contraseña" class="form-control" />
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Nombre</label>
        <input asp-for="nombre" type="text" placeholder="Nombre" class="form-control" />
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Apellido</label>
        <input asp-for="apellido" type="text" placeholder="Apellido" class="form-control" />
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">DNI</label>
        <input asp-for="dni" type="text" placeholder="DNI" class="form-control" />
    </div>

    <button type="submit" class="btn btn-outline-success">Guardar</button>
    <a asp-controller="Usuario" asp-action="Index" role="button" class="btn btn-outline-secondary">Volver</a>
</form>

Nueva carpeta/Login/Login.web/Views/Usuario/Editar.cshtml
@model Login.Usuario

<h1 class="display-5 mt-5">Editar Usuario</h1>

<form asp-controller="Usuario" asp-action="Editar" method="post">
    <div class="form-group">
        <label for="exampleInputEmail1">Username</label>
        <input asp-for="nombreUsuario" type="text" placeholder="Nombre de usuario" class="form-control" />
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input asp-for="contrasenia" type="password" placeholder="Contraseña" class="form-control" />
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Nombre</label>
        <input asp-for="nombre" type="text" placeholder="Nombre" class="form-control" />
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Apellido</label>
        <input asp-for="apellido" type="text" placeholder="Apellido" class="form-control" />
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">DNI</label>
        <input asp-for="dni" type="text" placeholder="DNI" class="form-control" />
    </div>

    <button type="submit" class="btn btn-outline-success">Guardar</button>
    <a asp-controller="Usuario" asp-action="Index" role="button" class="btn btn-outline-secondary">Volver</a>
</form>

Nueva carpeta/Login/Login.web/Views/Usuario/Index.cshtml
 @model IEnumerable<Login.Usuario>

<div class="row">
    <div class="col-10">
        <h2 class="display-4">Usuarios</h2>
    </div>
</div>
<br />
<a role="button" asp-controller="Usuario" asp-action="Agregar" class="btn btn-outline-primary">Agregar Usuario</a>
<br />
<br />
<p>Cantidad de Usuarios: <b>@ViewBag.CantidadUsuarios</b></p>
<table class="table table-dark table-striped table-responsive-md">
    <thead>
        <tr>
            <th>ID </th>

            <th>Nombre de Usuario </th>

            <th>Contraseña </th>

            <th>Opciones </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var usuario in Model)
        {
        <tr>
            <td>@usuario.idUsuario</td>
            <td>@usuario.nombreUsuario</td>
            <td>@usuario.contrasenia</td>
            <td>
                <a asp-controller="Usuario" asp-action="Editar" asp-route-id="@usuario.id" class="btn btn-link">Editar</a> |
                <a asp-controller="Usuario" asp-action="Eliminar" asp-route-id="@usuario.id" class="btn btn-link">Eliminar</a>
            </td>
        </tr>
        }
    </tbody>
</table>